# Generated by Django 6.0 on 2025-12-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend'), ('FULLSTACK', 'Fullstack'), ('ML', 'Machine Learning'), ('DL', 'Deep Learning'), ('AI', 'Artificial Intelligence'), ('LLM', 'Large Language Models'), ('CYBER', 'Cyber Security'), ('SWE', 'Software Engineering')], max_length=100),
        ),
    ]
